package com.department;

public enum Position {
    SOFTWARE_DEVELOPER,
    SOFTWARE_ENGINEER,
    SYSTEM_ANALYST,
    PROJECT_MANAGER,
    TEST_ENGINEER,
    GEOMATICS_ENGINEER,
    JOB_SECURITY_SPECIALIST


}
